### ISSUE TITLE
ImportError: No module named codis_client

### ISSUE THREAD

**Issue by lanji001** [weim0000/CodisClient#1]
您好！

我下载了zookeeper-3.4.6，执行了：
cd zookeeper-3.4.6/src/c/
./configure
make
make install

之后下载了CodisClient，执行了：
cd CodisClient/python/redis-py-2.4/
python setup.py install
cd ../zkpython-0.4.2/
python setup.py install

打开python的command line，执行 import redis 是可以的，并已经成功测试一个redis_server。但是执行import codis_client的时候，会报错误：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named codis_client

请问是哪个环境没有配置好？

**Comment by lanji001** [comment]
如果在 CodisClient/python/ 路径在启动python并import codis_client，这样可以保证找到 codis_client.py，但仍然会报错：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "codis_client.py", line 4, in <module>
    import zookeeper
  File "build/bdist.linux-x86_64/egg/zookeeper.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/zookeeper.py", line 6, in **bootstrap**
ImportError: libzookeeper_mt.so.2: cannot open shared object file: No such file or directory

但是在 /usr/local/lib 的路径下，是有 zookeeper_mt.so 文件的，并且 /usr/local/lib 已添加到 $PATH中。
